.circleci/config.yml
.circleci/php.ini
CHANGELOG.md
src/InfluxDB2/FluxCsvParser.php
src/InfluxDB2/QueryApi.php
tests/ClientTest.php
tests/FluxCsvParserTest.php
tests/QueryApiIntegrationTest.php
tests/QueryApiStreamTest.php
tests/WriteApiIntegrationTest.php

Closes #15
Fixed parsing QueryResponse on Windows

fix: avoid to use of eof over the stream => it not works on Windows

---

CHANGELOG.md
README.md
examples/WriteBatchingExample.php
src/InfluxDB2/WriteApi.php
src/InfluxDB2/WriteOptions.php
src/InfluxDB2/WriteType.php

Closes #23
1. Improved documentation about batching
2. `WriteOptions`, `WriteType` should be in an separate file - [see PSR-4: Autoloader](https://www.php-fig.org/psr/psr-4/)

feat: Improved documentation about batching, WriteOptions, WriteType should be in separate file

---

.circleci/config.yml
CHANGELOG.md
composer.json
src/InfluxDB2/WriteOptions.php

Closes #29 
This commit prevents invalid container access
by properly checking access in the respective places.
Also adds a CI test and updates dependencies for php 7.4.
Phpspec decided to not have a single version that's compatible with `php7.1` through `php7.4`, so I had to make the version constraint less restrictive. I hope thats fine.

update for php 7.4 compatibility

---

CHANGELOG.md
src/InfluxDB2/Point.php
tests/PointTest.php

Related to https://github.com/influxdata/influxdb-client-java/issues/127
* serialization of `\n`, `\r` and `\t` to Line Protocol
* `=` is valid sign for measurement name

fix: serialization of `\n`, `\r` and `\t` to Line Protocol, `=` is valid sign for measurement name 

---

CHANGELOG.md
README.md
src/InfluxDB2/WriteApi.php
src/InfluxDB2/WriteOptions.php
tests/WriteApiBatchingTest.php
tests/WriteApiTest.php

feat: Added retryInterval, maxRetries and maxRetryDelay to WriteApi

---

CHANGELOG.md
README.md
examples/WriteBatchingExample.php
src/InfluxDB2/Client.php
src/InfluxDB2/WriteOptions.php
tests/WriteApiBatchingTest.php
tests/WriteApiIntegrationTest.php

fix: Removed unused flushInterval from WriteApi

---

CHANGELOG.md
README.md
src/InfluxDB2/WriteApi.php
src/InfluxDB2/WriteOptions.php
tests/WriteApiBatchingTest.php
tests/WriteApiTest.php

Closes 
Added exponentialBase to WriteApi

feat: added exponentialBase to WriteApi

---

CHANGELOG.md
src/InfluxDB2/ApiException.php
src/InfluxDB2/DefaultApi.php
src/InfluxDB2/PointSettings.php
src/InfluxDB2/WriteApi.php
tests/WriteApiBatchingTest.php
tests/WriteApiTest.php

Closes #34 
Client now retries requests also when there is connection error.

feat: retry strategy for connection errors #34

---

CHANGELOG.md
README.md
src/InfluxDB2/WriteApi.php
src/InfluxDB2/WriteOptions.php
tests/WriteApiBatchingTest.php

feat: add jitterInterval to WriteApi

---

.circleci/config.yml
docker-compose.yml

- changed base image to `influxdb:2.0.0-rc`

chore: influxdb:2.0.0-rc is used as stable build

---

.gitignore
CHANGELOG.md
src/InfluxDB2/Client.php
src/InfluxDB2/DefaultApi.php
src/InfluxDB2/WriteApi.php
tests/BasicTest.php
tests/WriteApiBatchingTest.php

The message looks like:
_The retriable error occurred during writing of data. Reason: 'org 04014de4ed590000 has exceeded limited_write plan limit'. Retry in 5s._

feat: improved logging message for retries

---

CHANGELOG.md
README.md

Adding info about how to get the query in JSON format.
Closes #
When I was reading the README to find out how to get the response as a JSON formatted list it did not occur to me that I was to use the "Synchronous query", so I wanted to add that info. Maybe most people can work that out from the "result as a Array" but I did not.

docs: Update README.md

---

.circleci/config.yml
CHANGELOG.md
composer.json
src/InfluxDB2/DefaultApi.php

Closes #47
- Add support for Guzzle 7
- Add CI build for Guzzle 7

feat: add support for Guzzle 7

---

.circleci/config.yml
CHANGELOG.md
src/InfluxDB2/FluxCsvParser.php
tests/FluxCsvParserTest.php
tests/WriteApiTest.php

CSV parser is able to parse export from UI

feat: CSV parser is able to parse export from UI

---

.circleci/config.yml

XDEBUG should use coverage mode to avoid - "Use of undefined constant XDEBUG_CC_UNUSED"
https://app.circleci.com/pipelines/github/influxdata/influxdb-client-php/491/workflows/5827038f-74a1-4411-abec-bf80304b554b/jobs/1364

fix: CircleCI build with new XDEBUG v3

---

CHANGELOG.md
README.md
src/InfluxDB2/Client.php
src/InfluxDB2/UdpWriter.php
src/InfluxDB2/WriteApi.php
src/InfluxDB2/WritePayloadSerializer.php
src/InfluxDB2/Writer.php
tests/WriteUdpTest.php

Ability to write to DB via UDP protocol
See previous PR: https://github.com/influxdata/influxdb-client-php/pull/50

feat: UDP Writer

---

CHANGELOG.md
README.md
src/InfluxDB2/DefaultApi.php
tests/DefaultApiTest.php

Closes #55
Added possibility to disable verification of SSL certificate. https://docs.guzzlephp.org/en/stable/request-options.html#verify-option

feat: added possibility to disable verification of SSL certificate

---

.circleci/config.yml
CHANGELOG.md
docker-compose.yml

- Updated default docker image to `v2.0.3`
- Updated nightly docker image to `influxdb2:nightly`

chore(ci): update default docker image to v2.0.3

---

CHANGELOG.md
README.md
examples/DeleteDataExample.php

Closes #62
Added documentation and example how to delete data.

docs: documentation about delete endpoint

---

.circleci/config.yml
CHANGELOG.md
docker-compose.yml

- use `influxdb:latest` for stable InfluxDB 2
- use `quay.io/influxdb/influxdb:nightly` for nightly InfluxDB 2

chore(ci): use latest tag for InfluxDB 2, use correct image for InfluxDB 2 nightly

---

CHANGELOG.md
README.md
src/InfluxDB2/Client.php
src/InfluxDB2/DefaultApi.php

Closes #72 
I made it possible to change guzzleHttp timeout.
Sadly i couldn't get tests to work so I can't run them. But I did manual testing, i'm only using Client and `createWriteApi`.

feat: Allowed to change GuzzleHTTP timeout (#72)

---

.circleci/config.yml
CHANGELOG.md
README.md
src/InfluxDB2/DefaultApi.php
src/InfluxDB2/WriteApi.php
src/InfluxDB2/WriteOptions.php
src/InfluxDB2/WriteRetry.php
tests/WriteApiBatchingTest.php
tests/WriteApiTest.php

Improves exponential random retry strategy in write api like in python client https://github.com/influxdata/influxdb-client-python/pull/225
Delay is computed using random exponential backoff as a random value within the interval  ``retryInterval * exponentialBase^(attempts-1)`` and ``retryInterval * exponentialBase^(attempts)``. 
Example for ``retryInterval=5_000, exponentialBase=2, maxRetryDelay=125_000, total=5``
Retry delays are random distributed values within the ranges of ``[5_000-10_000, 10_000-20_000, 20_000-40_000, 40_000-80_000, 80_000-125_000]``

feat: exponential random retry

---

.circleci/config.yml
composer.json

Generated client sources are not compatible with the new version of guzzlehttp/psr7 2.0 
It also breaks circle ci builds, we need to stick on 1.X for now.

fix: stick on 1.X version of guzzlehttp/psr7

---

CHANGELOG.md
src/InfluxDB2/Point.php
tests/PointTest.php

Closes #80
Correct serialisation to LineProtocol for tags which are not a `string`.

fix: serialization tags which are not a string

---

CHANGELOG.md
src/InfluxDB2/FluxCsvParser.php
tests/FluxCsvParserTest.php

Related to https://github.com/influxdata/influxdb-client-java/issues/239
Fixed parsing `Inf+` for [histogram() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/histogram/).
```csv
#group,false,false,true,true,true,true,true,true,true,true,false,false
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,string,string,string,string,string,string,double,double
#default,_result,,,,,,,,,,,
,result,table,_start,_stop,_field,_measurement,language,license,name,owner,le,_value
,,0,2021-06-23T06:50:11.897825012Z,2021-06-25T06:50:11.897825012Z,stars,github_repository,C#,MIT License,influxdb-client-csharp,influxdata,0,0
,,0,2021-06-23T06:50:11.897825012Z,2021-06-25T06:50:11.897825012Z,stars,github_repository,C#,MIT …
```

fix: parsing infinite numbers

---

CHANGELOG.md
README.md
src/InfluxDB2/Client.php
src/InfluxDB2/DefaultApi.php
tests/DefaultApiTest.php

1. Added documentation for proxies and redirects
2. Added option to configure `proxy`
3. Added option to configure redirects

feat: add configuration option for `proxy` and `redirects`

---

CHANGELOG.md
README.md
src/InfluxDB2/Client.php
src/InfluxDB2/UdpWriter.php

Closes #91 
New configuration option for IPv4 or IPv6

feat: add configuration option for ipv4 or ipv6, defaults to ipv4

---

CHANGELOG.md
src/InfluxDB2/Client.php
src/InfluxDB2/WriteApi.php

When a worker is created for a flush of the worker on close, it will just create a new object which makes it harder for for the garbage collector to correctly free the unused objects because the Worker itself has a reference to the WriteApi object it called. This is especially frustrating for WriteType::SYNCHRONOUS which doesn't need workers at all.
---
The worker will be flushed when something calls close on the WriteApi. But the worker will still continue to hold an reference to the WriteApi. This prevents an easy cleanup of the WriteApi by the (non-cyclic) garbage collector.
---
The autoCloseable list of a client is only growing but is never cleared. This causes problems with the reference based garbage collection. But there is nothing more to process when all writers were closed.
This …

fix: Fix file descriptor leaks in WriteApi

---

CHANGELOG.md
src/InfluxDB2/FluxCsvParser.php
tests/QueryApiIntegrationTest.php

Closes #100 
Use [`fgetcsv`](https://www.php.net/manual/en/function.fgetcsv.php) for parsing lines of annotated CSV.

fix: parsing response with new lines

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
README.md
examples/ParameterizedQuery.php
examples/README.md
src/InfluxDB2/QueryApi.php
tests/QueryApiTest.php

This PR implements support for Parameterized Queries for InfluxDB Cloud.
https://docs.influxdata.com/influxdb/cloud/query-data/parameterized-queries
Closes #56

feat: add parameterized queries

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
composer.json

Closes #112
Closes #113
Drop supports for PHP 7.1. The v `7.1` is not supported by the Guzzle:

chore: drop support for PHP 7.1

---

CHANGELOG.md
src/InfluxDB2/Model/PermissionResource.php

Added missing `PermissionResource` types.

fix: add missing PermissionResource types from Cloud definition

---

CHANGELOG.md
src/InfluxDB2/Point.php
tests/PointTest.php

Using `DateTimeInterface` to be more compatible with all `DateTime` objects (like `DateTimeImmutable`) in `Point`.

feat: Using `DateTimeInterface` to be more compatible with all `DateTime`

---

src/InfluxDB2/Client.php

This removes the redundant `@template T` phpdoc above the `Client` class.
the phpdoc currently breaks PHPStan checks, but I cannot find any use for it in the repository.

docs: remove unused `@template T` in Client phpdoc

---

.circleci/config.yml

This PR fixes nightly build by freezing the `xdebug` to version `3.1.6`. This version also supports `PHP 7.2`. For more info see: https://pecl.php.net/package-changelog.php?package=xdebug&release=3.2.0.
**Failing CI build**:
https://app.circleci.com/pipelines/github/influxdata/influxdb-client-php/1538/workflows/0b67507c-e56c-41aa-b178-c7c9f0728267/jobs/4616

fix(ci): freeze xdebug version to 3.1.6 which also supports PHP 7.2

---

CHANGELOG.md
composer.json
src/InfluxDB2/Point.php
tests/PointTest.php
tests/StringableClass.php

Closes #145 
- add a TypeHint to Point->addTag(). PHP will auto-convert scalars and stringable values. Null-Values are handled like before
- auto-convert scalars, objects with __toString() and stringable objects
- if the value cannot be converted, throw an exception

feat: #145 try to convert non-string-tags to strings

---

CHANGELOG.md
src/InfluxDB2/DefaultApi.php
tests/DefaultApiTest.php

Changes the error thrown from something like this;
```
ErrorException
Undefined property: stdClass::$message
```
to something like this;
```
InfluxDB2\ApiException 
[500] Error connecting to the API (http://influxdb:8086/api/v2/query?org=-)(type error 1:35-1:76: function does not take a parameter "end", required params (start))
```

fix: More fool-proof error message handling

---

CHANGELOG.md
src/InfluxDB2/FluxCsvParser.php

Closes #162 
Added argument `escape`.

fix: PHP 8.4 - fgetcsv argument escape provided explicitly

---

CHANGELOG.md
src/InfluxDB2/WritePayloadSerializer.php

Replaces #161
Remove deprecation for implicitly nullable parameter types since php 8.4

fix: remove deprecation for implicitly nullable parameter types (replacement)
